[package]
name = "pm"
version = "0.1.0"
authors = ["Daniel Wagner-Hall <dawagner@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "=1.0.19", features = ["span-locations"] }
syn = { version = "=1.0.38", features = ["full"] }
